logging:
  level:
    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
      springframework:
        web: DEBUG
        security: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: jonathan
#    password: 123
    driverClassName: org.h2.Driver
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      enabled: true